kuaidi:
  way1:
    province: 江苏,浙江,上海,安徽
    init_weight: 1000
    init_price: 5
    extra_price: 2
  way2: 
    province: 山东,北京,广东,海南,河北,湖北,湖南,江西,福建,天津
    init_weight: 1000
    init_price: 7
    extra_price: 2
  way3: 
    province: 广西,河南,山西,四川,重庆
    init_weight: 1000
    init_price: 9
    extra_price: 2
  way4: 
    province: 贵州,黑龙江,吉林,辽宁,内蒙古,陕西,云南,甘肃,宁夏,青海
    init_weight: 1000
    init_price: 11
    extra_price: 2
  way5: 
    province: 西藏,新疆
    init_weight: 1000
    init_price: 18
    extra_price: 2


huodaofukuan:
  way1:
    province: 江苏,浙江,上海,安徽
    init_weight: 1000
    init_price: 6
    extra_price: 2
  way2: 
    province: 山东,北京,广东,海南,河北,湖北,湖南,江西,福建,天津
    init_weight: 1000
    init_price: 8
    extra_price: 2
  way3: 
    province: 广西,河南,山西,四川,重庆
    init_weight: 1000
    init_price: 10
    extra_price: 2
  way4: 
    province: 贵州,黑龙江,吉林,辽宁,内蒙古,陕西,云南,甘肃,宁夏,青海
    init_weight: 1000
    init_price: 12
    extra_price: 2
  way5: 
    province: 西藏,新疆
    init_weight: 1000
    init_price: 19
    extra_price: 2

